steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg',
         'CHATBOT_ECOSYSTEM_FILE=${_BOT_TYPE_1}.process.yaml',
         '-f',
         'chatbot.Dockerfile',
         '-t',
         'gcr.io/hoprassociation/hopr-chatbot/${_BOT_TYPE_1}',
         '.']
substitutions:
  _BOT_TYPE_1: coverbot
images:
- 'gcr.io/hoprassociation/hopr-chatbot/${_BOT_TYPE_1}'
