steps:
  - id: 'install-yarn'
    name: node:16
    entrypoint: yarn
    args: ['install']

  - id: 'build'
    waitFor: ['install-yarn']
    name: node:16
    entrypoint: yarn
    args: ['build']

  - name: 'gcr.io/kaniko-project/executor:latest'
    waitFor: ['build']
    args:
      - '--destination=gcr.io/$PROJECT_ID/hoprd:$_HOPR_IMAGE_VERSION'
      - '--build-arg=HOPRD_VERSION=$_HOPR_PACKAGE_VERSION'
      - --cache=true
      - --cache-ttl=4h

options:
  logStreamingOption: STREAM_ON
  machineType: N1_HIGHCPU_8
timeout: 630s
