steps:
  - id: 'download-cached-yarn-dependencies'
    waitFor: ['-']
    name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args:
      - '-c'
      - |
        gsutil cp gs://${PROJECT_ID}_cloudbuild/cache/yarn-dependencies.tgz yarn-dependencies.tgz || exit 0
        tar -zxf yarn-dependencies.tgz || exit 0

  - id: 'install-yarn'
    name: node:16
    waitFor: ['download-cached-yarn-dependencies']
    entrypoint: yarn
    args: ['install']

  - id: 'build'
    waitFor: ['install-yarn']
    name: node:16
    entrypoint: yarn
    args: ['build']

  - id: 'upload-cached-yarn-dependencies'
    waitFor: ['build']
    name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    dir: cloudcmr-front
    args:
      - '-c'
      - |
        tar -zcf yarn-dependencies.tgz ./node_modules
        gsutil cp yarn-dependencies.tgz gs://${PROJECT_ID}_cloudbuild/cache/yarn-dependencies.tgz

  - name: 'gcr.io/cloud-builders/docker'
    waitFor: ['build']
    args:
      - 'build'
      - '.'
      - '--tag=gcr.io/$PROJECT_ID/hoprd:$_HOPR_IMAGE_VERSION'
      - '--build-arg=HOPRD_VERSION=$_HOPR_PACKAGE_VERSION'

options:
  logStreamingOption: STREAM_ON
  machineType: N1_HIGHCPU_8
timeout: 630s
images:
  - 'gcr.io/$PROJECT_ID/hoprd'
