steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=gcr.io/hoprassociation/hoprd:debug
      - --cache=true
      - --cache-ttl=1h
options:
  logStreamingOption: STREAM_ON
  machineType: N1_HIGHCPU_8
timeout: 630s
