version: '3.4'
volumes:
  data: {}
services:
  hopr.avado.dnp.dappnode.eth:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    image: 'hopr.avado.dnp.dappnode.eth:0.0.4'
    restart: always
    volumes:
      - 'data:/data'
    ports:
      - '3000:3000'
    dns: 172.33.1.2
