version: '3.4'
volumes:
  data: {}
services:
  hopr.avado.dnp.dappnode.eth:
    build:
      context: hoprd
      dockerfile: ./Dockerfile
    image: 'hopr.avado.dnp.dappnode.eth:0.2.0'
    restart: always
    volumes:
      - 'data:/data'
    ports:
      - '3000:3000'
      - '53:53'
    dns:
      - 172.33.1.2
      - 8.8.8.8
