version: '3.1'

services:
  server:
    image: gcr.io/hoprassociation/hopr-server:v0.2.4-xdai
    restart: always
    ports:
      - '50051:50051'
      - '9091:9091'
    environment:
      - PROVIDER=wss://xdai.poanetwork.dev/wss
      - BOOTSTRAP_SERVERS=/ip4/34.65.158.118/tcp/9091/p2p/16Uiu2HAmNqLm83bwMq9KQEZEWHcbsHQfBkbpZx4eVSoDG4Mp6yfX
      - DEBUG=hopr*
    volumes:
      - /app/db
  chat-bot:
    image: gcr.io/hoprassociation/hopr-chatbot/client
    restart: always
    depends_on:
      - 'server'
    environment:
      - API_URL=server:50051
