version: '3.4'
services:
  hopr.avado.dnp.dappnode.eth:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - type: volume
        source: db
        target: /app/db
    ports:
      - '9091:9091'
      - '3000:3000'
      - '53:53'
    dns:
      - 172.33.1.2
      - 8.8.8.8
volumes:
  db: {}
