version: '3.4'
services:
  hopr.avado.dnp.dappnode.eth:
    build:
      context: ../hoprd
      dockerfile: ./Dockerfile
    entrypoint: ['node', '/app/index.js', '--password=open-sesame-iTwnsPNg0hpagP+o6T0KOwiH9RQ01', '--admin', '--init']
      args:
        network: bnb-testnet
    image: 'hopr.avado.dnp.dappnode.eth:1.57.2'
    restart: always
    volumes:
      - type: volume
        source: db
        target: /app/db
    ports:
      - '9091:9091'
      - '3000:3000'
      - '53:53'
    dns:
      - 172.33.1.2
      - 8.8.8.8
volumes:
  db: {}
