version: '3.4'
services:
  hopr.avado.dnp.dappnode.eth:
    build:
      context: ../hoprd
      dockerfile: ./Dockerfile
<<<<<<< HEAD
    image: 'hopr.avado.dnp.dappnode.eth:0.53.0'
=======
    image: 'hopr.avado.dnp.dappnode.eth:1.17.1'
>>>>>>> 8c8ef079e4a857f2ab561adb874b3303c008cc3c
    restart: always
    volumes:
      - type: volume
        source: db
        target: /app/db
    ports:
      - '3000:3000'
      - '53:53'
    dns:
      - 172.33.1.2
      - 8.8.8.8
volumes:
  db: {}
