steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '.'
      - '--tag=$_DOCKER_IMAGE:$_HOPR_IMAGE_VERSION'
      - '--build-arg=HOPRD_VERSION=$_HOPR_PACKAGE_VERSION'
options:
  logStreamingOption: STREAM_ON
images:
  - '$_DOCKER_IMAGE'
