name: HOPR End-to-end tests

on:
  push:
    branches: ['**']
    paths-ignore:
      - '**/docs/**/*'

jobs:
  e2e:
    name: Test Nr. ${{ matrix.number }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        number: [1, 2]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Restore cache of node modules.
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: |
          yarn

      - name: Build
        run: |
          yarn build

      - name: Test
        shell: bash {0}
        run: ./test/e2e/test_manager.sh ${{ matrix.number }}