name: Funding Account

on:
  push:
    branches: ['debug/**']
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    name: Funding Account
    runs-on: ubuntu-latest
    strategy:
      matrix:
        networks: ['matic']
        include:
          - networks: matic
            rpc_url: FUNDING_RPC_MATIC_URL
            token_address: "0x4774fEd3f2838f504006BE53155cA9cbDDEe9f0c"
            abi_function: "function balanceOf(address owner) view returns (uint256)"

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Install ethers
        run: npm install -g @ethersproject/cli

      - name: Check wallet address
        shell: bash {0}
        run: |
          echo "Address: $(ethers --account $RAW_KEY eval 'accounts[0].getAddress().then(address => address)')"
        env:
          RAW_KEY: ${{ secrets.FUNDING_WALLET_PRIVATE_KEY }}
          RPC_URL: ${{ secrets[matrix.rpc_url] }}

      - name: Check wallet balance
        shell: bash {0}
        run: |
          echo "Balance: $(ethers --rpc $RPC_URL --account $RAW_KEY eval 'accounts[0].getBalance().then(b => formatEther(b))')"
        env:
          RAW_KEY: ${{ secrets.FUNDING_WALLET_PRIVATE_KEY }}
          RPC_URL: ${{ secrets[matrix.rpc_url] }}

      - name: Check HOPR balance
        shell: bash {0}
        run: |
          echo "HOPR Tokens: $(ethers --rpc $RPC_URL --account $RAW_KEY eval 'accounts[0].getAddress().then(address => (new ethers.Contract(${{ matrix.token_address }},[${{ matrix.abi_function }}], new ethers.providers.JsonRpcProvider($RPC_URL))).balanceOf(address).then(b => formatEther(b)))')"
        env:
          RAW_KEY: ${{ secrets.FUNDING_WALLET_PRIVATE_KEY }}
          RPC_URL: ${{ secrets[matrix.rpc_url] }}