name: Funding Account

on:
  push:
    branches: ['debug/**']
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    name: Funding Account
    runs-on: ubuntu-latest
    strategy:
      matrix:
        networks: ['matic']
        include:
          - networks: matic
            rpc_url: FUNDING_RPC_MATIC_URL

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Install ethers
        run: npm install -g @ethersproject/cli

      - name: Check balance of wallets
        shell: bash {0}
        run: |
          echo "Funding Wallet: $ADDRESS"
          echo "Address Confirmation: $(ethers --acount $RAW_KEY eval 'accounts[0].getAddress().then(address => address)')"
          echo "Balance: $(ethers --rpc $RPC_URL --account $RAW_KEY eval 'accounts[0].getBalance().then(b => formatEther(b))')"
        env:
          RAW_KEY: ${{ secrets.FUNDING_WALLET_PRIVATE_KEY }}
          ADDRESS: ${{ secrets.FUNDING_WALLET_ADDRESS }}
          RPC_URL: ${{ secrets[matrix.rpc_url] }}