name: HOPR Workflow
on: [push, pull_request]

jobs:
  build:
    name: Build, Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-${{ matrix.node-version }}-build-${{ hashFiles(env.pkgPath) }}
      - name: Install node modules
        working-directory: ${{ env.workDir }}
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile
      - name: Build library
        working-directory: ${{ env.workDir }}
        run: |
          yarn build
      - name: Test library
        working-directory: ${{ env.workDir }}
        run: |
          yarn test

  publish_minor:
    name: Publish Minor Version Bump(NPM, Github)
    needs: build

    if: github.event_name == 'pull_request' # && github.ref == 'refs/heads/master' && contains(github.event.pull_request.labels.*.name, 'minor')

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set name / email for commit
        run: git config --global user.email "noreply@hoprnet.org" && git config --global user.name "HOPR Versioning robot"
      - name: Bump package.json
        run: npm version minor
      - name: Commit back to master
        run: git fetch origin && git push origin HEAD:master

      #- name: NPM Publish
      #  run: npm publish
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
