name: HOPR Workflow
on:
  push:
    branches: ['**']
    paths-ignore:
      - 'docs/**'
      - 'websites/**'
jobs:
  build:
    name: Build, Test, Publish etc
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12]
        yarn-version: [1]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - name: Install node modules
        run: |
          yarn policies set-version ${{ matrix.yarn-version }}
          yarn install --pure-lockfile
      - name: Install dependencies
        run: |
          yarn util:install
      - name: Lint & Fix
        if: |
          github.event_name == 'pull_request' &&
          github.event.action == 'closed' &&
          github.event.pull_request.merged == true
        run: |
          git config --global user.email "noreply@hoprnet.org" && git config --global user.name "HOPR Linting robot"
          yarn lint:fix
          git commit -a -m "Fix linting"
      - name: Link & Build
        run: |
          yarn util:link && yarn util:build
      - name: Test
        run: |
          yarn test
      - name: Test Docker build hoprd 
        working-directory: packages/hoprd
        run: docker build .
