name: HOPR Lint fix

on:
  push:
    branches: ['**']

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install dependencies
        run: |
          yarn install

      - name: Run linter
        run: |
          yarn lint:fix

      - name: Check if changed
        id: check-changed
        run: |
          echo "::set-output name=changed::$(git status --porcelain)"

      - name: Commit changes
        if: steps.check-changed.outputs.changed != ''
        run: |
          git config --global user.email "noreply@hoprnet.org"
          git config --global user.name "HOPR Linting robot"
          git commit -a -m "Fix linting" || true
          git pull origin ${{ github.ref }}
          git push origin ${{ github.ref }}
