name: Smoke test
on:
  push:
    branches: ['**']
    paths-ignore:
      - 'docs/**'
      - 'websites/**'

jobs:
  build:
    name: Smoke testing 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Temporarily install everything
        run: |
          yarn install --pure-lockfile
          yarn util:install
          yarn util:link && yarn util:build

          #- name: Install hoprd
          #shell: bash
          #run: |
          #NODE_ENV=production npm install -g @hoprnet/hoprd
          #working-directory: packages/hoprd

      - name: Check databases
        shell: bash
        run: |
          shopt -s expand_aliases
          alias hoprd="node packages/hoprd/lib/index.js"

          hoprd --data='./test/fixtures/alice' --password="$DBPASS" --run "myAddress hopr" || true
          hoprd --data='./test/fixtures/bob' --password="$DBPASS" --run "myAddress hopr" || true
          hoprd --data='./test/fixtures/charlie' --password="$DBPASS" --run "myAddress hopr" || true
        env:
          DBPASS: ${{ secrets.SMOKETESTPASSWORD }}

      - name: Commit database changes back to repo
        run: |
          git config --global user.email "noreply@hoprnet.org" && git config --global user.name "HOPR Testing robot"
          git add ./test || true
          git commit -a || true
          git pull origin ${{ github.ref }}
          git push origin ${{ github.ref }} || true
