name: HOPR Test

on:
  push:
    branches: ['**']
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12]
        package: ['@hoprnet/hopr-core', '@hoprnet/hopr-ethereum', 'all']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-modules-${{ matrix.package }}-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: |
          yarn
          yarn setup
      - name: Build (all)
        if: matrix.package == 'all' 
        run: |
          node_modules/.bin/lerna run build --ignore core --ignore ethereum

      - name: Test (all)
        if: matrix.package == 'all'
        run: |
          node_modules/.bin/lerna run test --ignore core --ignore ethereum

      - name: Build ${{ matrix.package }}
        if: matrix.package != 'all'
        run: |
          node_modules/.bin/lerna run build --scope ${{ matrix.package }}
      - name: Test ${{ matrix.package }}
        if: matrix.package != 'all' 
        run: |
          node_modules/.bin/lerna run test --scope ${{ matrix.package }}

#      - name: Test Docker build hoprd
#        working-directory: packages/hoprd
#        run: docker build .
