name: HOPR Testnet

env:
  HOPR_GITHUB_REF: ${{ github.ref }}

on:
  push:
    branches: ['testnet/**']
    paths-ignore:
      - 'docs/**/*'
      - 'packages/*/docs/**/*'

jobs:
  build_hoprd_docker:
    name: Build HOPRD Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git info
        run: ./scripts/configure-git-info.sh

      - name: Setup Google Cloud Credentials
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}
          export_default_credentials: true

      - name: Set image version
        id: set-image-version
        run: echo "::set-output name=vsn::$(date +%s)"

      - name: Set package version
        id: set-package-version
        run: echo "::set-output name=vsn::$(./scripts/get-package-version.sh)"
        env:
          HOPR_PACKAGE: hoprd

      - name: Set latest release tag
        id: set-latest-release-tag
        run: |
          # we must set the tag specific to the release to prevent overrides
          # from other release branches
          declare release_name=${HOPR_GITHUB_REF##refs/heads/testnet/}
          declare tag="latest-${release_name}"
          echo "::set-output name=tag::${tag}"

      - name: Building Docker image using Google Cloud Build
        working-directory: packages/hoprd
        run: |
          gcloud builds submit --config cloudbuild.yaml \
            --substitutions=_HOPR_PACKAGE_VERSION=${HOPR_PACKAGE_VERSION},_HOPR_IMAGE_VERSION=${HOPR_IMAGE_VERSION}
        env:
          HOPR_PACKAGE: hoprd
          HOPR_DOCKER_IMAGE: gcr.io/hoprassociation/hoprd
          HOPR_IMAGE_VERSION: ${{ steps.set-image-version.outputs.vsn }}
          HOPR_PACKAGE_VERSION: ${{ steps.set-package-version.outputs.vsn }}

      - name: Verify the correct hoprd package version has been bundled
        run: |
          declare v=$(docker run --pull always ${HOPR_DOCKER_IMAGE}:${HOPR_IMAGE_VERSION} --version 2> /dev/null | sed -n '3p')
          [ "${v}" = "${HOPR_PACKAGE_VERSION}" ]
        env:
          HOPR_DOCKER_IMAGE: gcr.io/hoprassociation/hoprd
          HOPR_IMAGE_VERSION: ${{ steps.set-image-version.outputs.vsn }}
          HOPR_PACKAGE_VERSION: ${{ steps.set-package-version.outputs.vsn }}

      - name: Add additional tags to new Docker image (on master and release branches)
        if: ${{ (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/testnet/')) && !env.ACT }}
        run: |
          gcloud container images add-tag ${HOPR_DOCKER_IMAGE}:${HOPR_IMAGE_VERSION} ${HOPR_DOCKER_IMAGE}:${HOPR_PACKAGE_VERSION}
        env:
          HOPR_DOCKER_IMAGE: gcr.io/hoprassociation/hoprd
          HOPR_IMAGE_VERSION: ${{ steps.set-image-version.outputs.vsn }}
          HOPR_PACKAGE_VERSION: ${{ steps.set-package-version.outputs.vsn }}

      - name: Add tag for latest release to new Docker image on release branches
        if: ${{ !env.ACT &&  startsWith(github.ref, 'refs/heads/testnet/') }}
        run: |
          gcloud container images add-tag ${HOPR_DOCKER_IMAGE}:${HOPR_IMAGE_VERSION} ${HOPR_DOCKER_IMAGE}:${TAG}
        env:
          HOPR_DOCKER_IMAGE: gcr.io/hoprassociation/hoprd
          HOPR_IMAGE_VERSION: ${{ steps.set-image-version.outputs.vsn }}
          TAG: ${{ steps.set-latest-release-tag.outputs.tag }}

  avado:
    name: Build Avado
    runs-on: ubuntu-latest
    needs: [build_hoprd_docker]
    steps:
      - uses: actions/checkout@v2

      - name: Configure Git info
        run: ./scripts/configure-git-info.sh

      - name: Build Avado
        working-directory: packages/avado
        env:
          HOPR_GIT_MSG: "placeholder"
          HOPR_GITHUB_REF: ${{ github.ref }}
          AVADO_VERSION: ${{ steps.set-version.outputs.vsn }}
        run: |
          docker-compose build
          sudo npm install -g git+https://github.com/AvadoDServer/AVADOSDK.git#c11c4bd
          cat ./dappnode_package.json
          sudo avadosdk build --provider http://80.208.229.228:5001
          git add dappnode_package.json docker-compose.yml releases.json
          git commit -m "Avado CI: new release"
          # http://go.ava.do/install/<IPFS HASH>

      - name: Commit & Push changes
        if: ${{ !env.ACT }}
        env:
          HOPR_GIT_MSG: "Avado CI: new release"
          HOPR_GITHUB_REF: ${{ github.ref }}
        run: ./scripts/commit-and-push-all-changes.sh

      - name: Send notification if anything failed on master or release branches
        if: ${{ failure() && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')) && !env.ACT }}
        run: |
          ./scripts/notify-matrix-github-workflow-failure.sh "${MATRIX_ROOM}" "${{ github.repository }}" \
            "${{ github.workflow }}" "${{ github.run_id }}"