name: Update AVADO Node

on: workflow_dispatch

jobs: 
  build:
    name: Build for Avado
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodule
        uses: actions/checkout@v2.0.0
        with:
          repository: hoprnet/hoprd
          path: hoprd
          ref: 'avado'
      - name: Build Docker
        run: |
          docker-compose build

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dappnodesdk
        run: sudo npm install -g @dappnode/dappnodesdk
      - name: Bump Dappnode version
        run: dappnodesdk increase minor
      - name: Build on dappnode
        run: dappnodesdk build



